name: topnba
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  http: ^0.12.1
  material_design_icons_flutter: 4.0.5345
  flutter_launcher_name: ^0.0.1
  font_awesome_flutter: ^8.8.1
  flappy_search_bar: 1.4.1
  flutter_linkify: ^3.1.3
  url_launcher: ^5.5.0
  flutter_slidable: ^0.5.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "icons/launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/team_logos/chicago_bulls.png
      - assets/team_logos/atlanta_hawks.png
      - assets/team_logos/boston_celtics.png
      - assets/team_logos/brooklyn_nets.png
      - assets/team_logos/charlotte_hornets.png
      - assets/team_logos/cleveland_cavaliers.png
      - assets/team_logos/dallas_mavericks.png
      - assets/team_logos/denver_nuggets.png
      - assets/team_logos/detroit_pistons.png
      - assets/team_logos/golden_state_warriors.png
      - assets/team_logos/houston_rockets.png
      - assets/team_logos/indiana_pacers.png
      - assets/team_logos/la_clippers.png
      - assets/team_logos/los_angeles_lakers.png
      - assets/team_logos/memphis_grizzlies.png
      - assets/team_logos/miami_heat.png
      - assets/team_logos/milwaukee_bucks.png
      - assets/team_logos/minnesota_timberwolves.png
      - assets/team_logos/new_orleans_pelicans.png
      - assets/team_logos/new_york_knicks.png
      - assets/team_logos/oklahoma_city_thunder.png
      - assets/team_logos/orlando_magic.png
      - assets/team_logos/philadelphia_76ers.png
      - assets/team_logos/phoenix_suns.png
      - assets/team_logos/trail_blazers.png
      - assets/team_logos/sacramento_kings.png
      - assets/team_logos/san_antonio_spurs.png
      - assets/team_logos/toronto_raptors.png
      - assets/team_logos/utah_jazz.png
      - assets/team_logos/washington_wizards.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
